export interface ChannelResourceItem {
  type?: 'LLM' | 'CLOUD' | 'PAY' | 'SEARCH' | 'VIDEO' | 'SPEECH' | 'EMBEDDING' | 'FILES' | 'MODERATION' | 'AUDIO' | 'MUSIC' | 'NEWS' | 'IMAGE' | 'VECTOR_STORE' | 'MEMORY' | 'KNOWLEDGE_BASE' | 'DATA_SOURCE' | 'AGENT' | 'OAUTH' | 'TOOL' | 'PROMPT' | 'SMS' | 'OFFICIAL_ACCOUNT' | 'MINI_PROGRAM' | 'OCR' | 'APPSTORE' | 'OBJECT_STORAGE' | 'RTC' | 'IM' | 'IOT';
  functions?: ('NONE' | 'SPEECH_SYNTHESIS' | 'SPEECH_TRANSCRIPTION' | 'SPEECH_TRANSLATION')[];
}
