import type { AgentAccountConfig } from './agent-account-config';
import type { ApiKeyAccountConfig } from './api-key-account-config';
import type { AppStoreAccountConfig } from './app-store-account-config';
import type { AudioAccountConfig } from './audio-account-config';
import type { ChannelResourceInfo } from './channel-resource-info';
import type { CloudAccountConfig } from './cloud-account-config';
import type { DatasourceAccountConfig } from './datasource-account-config';
import type { EmbeddingAccountConfig } from './embedding-account-config';
import type { FilesAccountConfig } from './files-account-config';
import type { ImAccountConfig } from './im-account-config';
import type { ImageAccountConfig } from './image-account-config';
import type { IotAccountConfig } from './iot-account-config';
import type { KnowledgeAccountConfig } from './knowledge-account-config';
import type { LlmAccountConfig } from './llm-account-config';
import type { MemoryAccountConfig } from './memory-account-config';
import type { MiniProgramAccountConfig } from './mini-program-account-config';
import type { ModerationAccountConfig } from './moderation-account-config';
import type { MusicAccountConfig } from './music-account-config';
import type { NewsAccountConfig } from './news-account-config';
import type { OAuthAccountConfig } from './oauth-account-config';
import type { OcrAccountConfig } from './ocr-account-config';
import type { OfficialAccountConfig } from './official-account-config';
import type { OssAccountConfig } from './oss-account-config';
import type { PayAccountConfig } from './pay-account-config';
import type { RtcAccountConfig } from './rtc-account-config';
import type { SearchAccountConfig } from './search-account-config';
import type { SmsAccountConfig } from './sms-account-config';
import type { ToolAccountConfig } from './tool-account-config';
import type { VectorAccountConfig } from './vector-account-config';
import type { VideoAccountConfig } from './video-account-config';

export interface ModelConfig {
  id?: number;
  uuid?: string;
  weight?: number;
  channel?: 'DEFAULT' | 'ALIYUN' | 'AWS' | 'APPLE' | 'AZURE' | 'BAIDU' | 'VOLCENGINE' | 'TENCENT' | 'HUAWEI' | 'GOOGLE' | 'META' | 'WECHAT' | 'ALIPAY' | 'UNION_PAY' | 'UNIONPAY' | 'DOUYIN' | 'MICROSOFT' | 'AMAZON' | 'ANTHROPIC' | 'XAI' | 'DEEPSEEK' | 'GROQ' | 'HUGGING_FACE' | 'KUAISHOU' | 'MINIMAX' | 'MISTRAL' | 'MOONSHOT' | 'NVIDIA' | 'OPENAI' | 'OLLAMA' | 'PERPLEXITY' | 'SDKWORK' | 'SILICONFLOW' | 'STEPFUN' | 'XUNFEI' | 'ZHIPU' | 'RAGFLOW' | 'STABILITY' | 'MINDSDB' | 'MEM0' | 'BOCHA' | 'BING' | 'OPEN_ROUTER' | 'STRIPE' | 'PAYPAL' | 'SUNO' | 'VIDU' | 'RUNWAY' | 'MEITUAN' | 'YUNWU' | 'MIDJOURNEY' | 'IDEOGRAM' | 'FLUX' | 'VECTOR_STORE_AZURE' | 'VECTOR_STORE_CASSANDRA' | 'VECTOR_STORE_CHROMA' | 'VECTOR_STORE_COUCHBASE' | 'VECTOR_STORE_ELASTICSEARCH' | 'VECTOR_STORE_GEMFIRE' | 'VECTOR_STORE_MARIADB' | 'VECTOR_STORE_MILVUS' | 'VECTOR_STORE_MONGODB' | 'VECTOR_STORE_NEO4J' | 'VECTOR_STORE_OPENSEARCH' | 'VECTOR_STORE_ORACLE' | 'VECTOR_STORE_PGVECTOR' | 'VECTOR_STORE_PINECONE' | 'VECTOR_STORE_QDRANT' | 'VECTOR_STORE_REDIS' | 'VECTOR_STORE_TYPESENSE' | 'VECTOR_STORE_WEAVIATE';
  product?: string;
  agent?: AgentAccountConfig;
  appStore?: AppStoreAccountConfig;
  apikey?: ApiKeyAccountConfig;
  audio?: AudioAccountConfig;
  cloud?: CloudAccountConfig;
  datasource?: DatasourceAccountConfig;
  embedding?: EmbeddingAccountConfig;
  files?: FilesAccountConfig;
  im?: ImAccountConfig;
  image?: ImageAccountConfig;
  iot?: IotAccountConfig;
  knowledge?: KnowledgeAccountConfig;
  llm?: LlmAccountConfig;
  memory?: MemoryAccountConfig;
  moderation?: ModerationAccountConfig;
  music?: MusicAccountConfig;
  miniProgram?: MiniProgramAccountConfig;
  news?: NewsAccountConfig;
  ocr?: OcrAccountConfig;
  official?: OfficialAccountConfig;
  oss?: OssAccountConfig;
  pay?: PayAccountConfig;
  rtc?: RtcAccountConfig;
  search?: SearchAccountConfig;
  sms?: SmsAccountConfig;
  tool?: ToolAccountConfig;
  vector?: VectorAccountConfig;
  video?: VideoAccountConfig;
  voice?: AudioAccountConfig;
  resources?: ChannelResourceInfo;
  properties?: Record<string, unknown>;
  oauth?: OAuthAccountConfig;
}
