/** RBAC Permission Value Object (stores system permission metadata) */
export interface PlusPermissionVO {
  /** Creation time, set when entity is first persisted */
  createdAt?: string;
  /** Last update time, updated when entity is modified */
  updatedAt?: string;
  /** Primary key ID, generated by database */
  id?: number;
  /** Universally unique identifier UUID */
  uuid?: string;
  /** Permission display name (human-readable identifier) */
  name?: string;
  /** Permission unique code (programmatic identifier) */
  code?: string;
  /** Permission description (functional details) */
  description?: string;
  /** Permission status (ENABLED/DISABLED) */
  status?: 'ACTIVE' | 'INACTIVE';
  /** Display sort order (lower values appear first) */
  sortOrder?: number;
  /** Associated resource URL (for web/api permissions) */
  resourceUrl?: string;
  /** HTTP method (for API permissions, empty for menu permissions) */
  httpMethod?: string;
}
