import type { AgentKnowledgeConfig } from './agent-knowledge-config';
import type { AgentMemoryConfig } from './agent-memory-config';
import type { AgentToolConfig } from './agent-tool-config';
import type { AiAgentSystemPrompt } from './ai-agent-system-prompt';
import type { ImageMediaResource } from './image-media-resource';
import type { PlusAiAgentConfig } from './plus-ai-agent-config';
import type { PlusChatOptions } from './plus-chat-options';
import type { SpeechConfig } from './speech-config';
import type { TagsContent } from './tags-content';
import type { TeamAgentMembers } from './team-agent-members';
import type { VideoMediaResource } from './video-media-resource';

/** AI agent creation form with configuration details */
export interface PlusAiAgentForm {
  /** Agent name (unique identifier) */
  name: string;
  /** Agent face image */
  faceImage?: ImageMediaResource;
  /** Agent face video */
  faceVideo?: VideoMediaResource;
  /** Owner type */
  owner?: 'DEFAULT' | 'TENANT' | 'ORGANIZATION';
  /** Owner ID */
  ownerId?: number;
  /** Service provider */
  channel?: 'DEFAULT' | 'ALIYUN' | 'AWS' | 'APPLE' | 'AZURE' | 'BAIDU' | 'VOLCENGINE' | 'TENCENT' | 'HUAWEI' | 'GOOGLE' | 'META' | 'WECHAT' | 'ALIPAY' | 'UNION_PAY' | 'UNIONPAY' | 'DOUYIN' | 'MICROSOFT' | 'AMAZON' | 'ANTHROPIC' | 'XAI' | 'DEEPSEEK' | 'GROQ' | 'HUGGING_FACE' | 'KUAISHOU' | 'MINIMAX' | 'MISTRAL' | 'MOONSHOT' | 'NVIDIA' | 'OPENAI' | 'OLLAMA' | 'PERPLEXITY' | 'SDKWORK' | 'SILICONFLOW' | 'STEPFUN' | 'XUNFEI' | 'ZHIPU' | 'RAGFLOW' | 'STABILITY' | 'MINDSDB' | 'MEM0' | 'BOCHA' | 'BING' | 'OPEN_ROUTER' | 'STRIPE' | 'PAYPAL' | 'SUNO' | 'VIDU' | 'RUNWAY' | 'MEITUAN' | 'YUNWU' | 'MIDJOURNEY' | 'IDEOGRAM' | 'FLUX' | 'VECTOR_STORE_AZURE' | 'VECTOR_STORE_CASSANDRA' | 'VECTOR_STORE_CHROMA' | 'VECTOR_STORE_COUCHBASE' | 'VECTOR_STORE_ELASTICSEARCH' | 'VECTOR_STORE_GEMFIRE' | 'VECTOR_STORE_MARIADB' | 'VECTOR_STORE_MILVUS' | 'VECTOR_STORE_MONGODB' | 'VECTOR_STORE_NEO4J' | 'VECTOR_STORE_OPENSEARCH' | 'VECTOR_STORE_ORACLE' | 'VECTOR_STORE_PGVECTOR' | 'VECTOR_STORE_PINECONE' | 'VECTOR_STORE_QDRANT' | 'VECTOR_STORE_REDIS' | 'VECTOR_STORE_TYPESENSE' | 'VECTOR_STORE_WEAVIATE';
  /** External channel ID */
  channelId?: string;
  /** Agent icon URL/path (e.g., "https://example.com/icon.png") */
  icon?: string;
  /** Agent description (detailed functionality explanation) */
  description?: string;
  /** Agent tags (comma-separated, e.g., "chat,tool,ai") */
  tags?: TagsContent;
  /** Agent type (1: Chat, 2: Tool, 3: Custom) */
  type: 'AGENT' | 'CHAT' | 'TOOL' | 'CUSTOM' | 'TEAM';
  /** Agent business type (e.g., TRANSLATION, CUSTOMER_SERVICE, WRITER, etc.) */
  bizType?: 'TRANSLATION' | 'CUSTOMER_SERVICE' | 'DATA_ANALYSIS' | 'CONTENT_GENERATION' | 'AUTO' | 'ASSISTANT_BUILDER' | 'HTTP_ADAPTER' | 'DIRECT' | 'SIMPLE' | 'CHAT_BOT' | 'PLAN' | 'ENHANCE_AGENT_DEFINITION' | 'ENHANCE_TOOL_DEFINITION' | 'INTENT' | 'OPEN_PLATFORM' | 'CHARACTER' | 'OFFICIAL_ACCOUNT' | 'OFFICIAL_ACCOUNT_MENU' | 'MEMORY' | 'MEMORY_EXTRACT' | 'MEMORY_UPDATE' | 'PROJECT_CREATE' | 'PROJECT_CREATE_PPT' | 'PROJECT_CREATE_APP_HTML' | 'PROJECT_CREATE_APP_VUE' | 'PROJECT_CREATE_APP_FLUTTER' | 'PROJECT_CREATE_APP_UNIAPP' | 'PROJECT_CREATE_APP_REACT' | 'PROJECT_CREATE_VIDEO' | 'PROJECT_CREATE_POSTER' | 'COMPANION_PET' | 'COMPANION_HUMAN' | 'TEAM' | 'DOCS' | 'DOCS_MARKDOWN_TO_HTML' | 'DOCS_HTML_TO_MARKDOWN' | 'DOCS_PPT_MARKDOWN_GENERATE' | 'DOCS_PPT_JSON_GENERATE' | 'DOCS_PPT_JSON_PROJECT_GENERATE' | 'DOCS_PPT_OUTLINE' | 'DOCS_BUSINESS_PLAN_ANALYST' | 'DOCS_BUSINESS_PLAN_WRITER' | 'FLOW_PLANING' | 'FLOW_CREATE' | 'IOT_DEVICE' | 'PLANING_PAGES' | 'PLANING_PAGES_APP' | 'PLANING_PAGES_WEB' | 'PLANING_PROJECT_README' | 'CODE' | 'CODE_JAVA_CONTROLLER' | 'CODE_JAVA_DTO' | 'CODE_JAVA_FORM' | 'CODE_JAVA_JPA_ENTITY' | 'CODE_JAVA_REPOSITORY' | 'CODE_JAVA_SERVICE' | 'CODE_JAVA_VO' | 'CODE_JAVA_ALL_IN_ONE' | 'CODE_JAVA_CODE' | 'CODE_JAVA_CODE_FROM_TYPESCRIPT' | 'CODE_JAVA_CHANNEL_MODEL' | 'CODE_FLUTTER_COMPONENT' | 'CODE_FLUTTER_PAGE' | 'CODE_FLUTTER_SITE_PROJECT' | 'CODE_FLUTTER_SERVICE' | 'CODE_FLUTTER_CONTROLLER' | 'CODE_FLUTTER_BINDINGS' | 'CODE_FLUTTER' | 'CODE_HTML_PAGE' | 'CODE_HTML_SITE_PROJECT' | 'CODE_HTML_PPT_PAGE' | 'CODE_HTML' | 'CODE_PYTHON_CONTROLLER' | 'CODE_PYTHON_SERVICE' | 'CODE_PYTHON_VO' | 'CODE_PHP_CONTROLLER' | 'CODE_PHP_SERVICE' | 'CODE_PHP_VO' | 'CODE_GO_CONTROLLER' | 'CODE_GO_SERVICE' | 'CODE_GO_VO' | 'CODE_RUST_CONTROLLER' | 'CODE_RUST_SERVICE' | 'CODE_RUST_VO' | 'CODE_REACT_COMPONENT' | 'CODE_REACT_PAGE' | 'CODE_REACT_SERVICE' | 'CODE_REACT_VO' | 'CODE_REACT_CONTROLLER' | 'CODE_REACT_API' | 'CODE_REACT_CONFIG' | 'CODE_REACT_ROUTER' | 'CODE_REACT_STYLE' | 'CODE_REACT_SITE_PROJECT' | 'CODE_REACT' | 'CODE_UNIAPP_COMPONENT' | 'CODE_UNIAPP_PAGE' | 'CODE_UNIAPP_SERVICE' | 'CODE_UNIAPP_SITE_PROJECT' | 'CODE_UNIAPP' | 'CODE_VUE_COMPONENT' | 'CODE_VUE_SITE_PROJECT' | 'CODE_VUE_PAGE' | 'CODE_VUE_PAGE_LIST' | 'CODE_VUE_PAGE_DETAIL' | 'CODE_VUE_PAGE_CREATE_OR_EDIT' | 'CODE_VUE' | 'CODE_VUE_COMPONENT_LIST' | 'CODE_VUE_COMPONENT_DETAIL' | 'CODE_VUE_COMPONENT_CREATE_OR_EDIT' | 'CODE_EVALUATOR' | 'CODE_EVALUATOR_JAVA' | 'CODE_EVALUATOR_PYTHON' | 'CODE_EVALUATOR_GO' | 'CODE_EVALUATOR_RUST' | 'CODE_EVALUATOR_PHP' | 'CODE_EVALUATOR_FLUTTER' | 'CODE_EVALUATOR_REACT' | 'CODE_EVALUATOR_UNIAPP' | 'CODE_EVALUATOR_VUE' | 'CODE_EVALUATOR_HTML' | 'CODE_EVALUATOR_HTML_PAGE' | 'CODE_EVALUATOR_HTML_PPT_PAGE' | 'CODE_EVALUATOR_HARMONYOS' | 'CODE_EVALUATOR_ARKTS' | 'CODE_VUE_CONVERT_HTML' | 'CODE_REACT_CONVERT_HTML' | 'CODE_UNIAPP_CONVERT_HTML' | 'CODE_FLUTTER_CONVERT_HTML' | 'CODE_JSON' | 'CODE_HARMONYOS' | 'CODE_HARMONYOS_COMPONENT' | 'CODE_HARMONYOS_PAGE' | 'CODE_HARMONYOS_SERVICE' | 'CODE_HARMONYOS_SITE_PROJECT' | 'CODE_ARKTS' | 'CODE_ARKTS_COMPONENT' | 'CODE_ARKTS_PAGE' | 'CODE_ARKTS_SERVICE' | 'TOOL_CHOOSE' | 'CODE_TYPESCRIPT_SERVICE' | 'VIDEO_PROMPT_GENERATE' | 'VIDEO_PROJECT' | 'VIDEO_AUTO_CUT' | 'VIDEO_SCENES' | 'IMAGE_PROMPT_GENERATE' | 'IMAGE_PROMPT_ARTICLE_COVER_GENERATE' | 'MUSIC_PROMPT_GENERATE' | 'MUSIC_LYRICS_GENERATE' | 'WRITER' | 'WRITER_ARTICLE' | 'WRITER_ARTICLE_IMAGE_PROMPT' | 'WRITER_IMAGE_PROMPT' | 'WRITER_NEWS' | 'WRITER_NOVEL' | 'WRITER_NOVEL_STORY_ARCHITECT' | 'WRITER_SCRIPT' | 'WRITER_CHAPTER' | 'WRITER_LYRICS' | 'WRITER_EVALUATOR' | 'WRITER_EVALUATOR_ARTICLE' | 'WRITER_EVALUATOR_NOVEL' | 'WRITER_EVALUATOR_SCRIPT' | 'WRITER_EVALUATOR_NEWS' | 'WRITER_EVALUATOR_LYRICS' | 'DATA_DATASOURCE' | 'DATA_CREATE_DATABASE' | 'DATA_CREATE_TABLE' | 'DATA_CREATE_COLUMN' | 'DATA_TABLE_GENERATE_ROWS' | 'DATA_CATEGORY_GENERATE' | 'DATA_CATEGORY_CLASSIFY' | 'DATA_INDUSTRY_GENERATE' | 'DATA_PRODUCT_GENERATE' | 'DATA_PRODUCT_ATTRIBUTE_GENERATE' | 'DATA_SKU_GENERATE' | 'DATA_SKU_ATTRIBUTE_GENERATE' | 'DATA_BRAND_GENERATE' | 'DATA_CATEGORY_ECOM_GENERATE' | 'DATA_KNOWLEDGE_BASE' | 'DATA_SEARCH_NEWS' | 'DATA_SEARCH_CONTENT' | 'DATA_SEARCH_WEB' | 'PROMPT_GENERATE' | 'PROMPT_OPTIMIZER' | 'PROMPT_ASSISTANT_BUILDER' | 'PROMPT_SYSTEM_GENERATE' | 'PROMPT_OPTIMIZER_IMAGE' | 'PROMPT_OPTIMIZER_VIDEO' | 'PROMPT_OPTIMIZER_MUSIC' | 'PROMPT_VOICE_CLONE_WORDS' | 'GAME_CHESS' | 'GAME_CHESS_JUDGE' | 'GAME_CHINESE_CHESS' | 'GAME_CHINESE_CHESS_JUDGE' | 'GAME_GOMOKU' | 'GAME_GOMOKU_JUDGE' | 'GAME_POKER' | 'GAME_POKER_JUDGE' | 'EDU_EDUCATION' | 'ECOMMERCE' | 'ECOMMERCE_SHOPPING_GUIDE' | 'RECRUITMENT' | 'TEAM_APP' | 'TEAM_AUDIO' | 'TEAM_CHAT' | 'TEAM_DOCS' | 'TEAM_IMAGE' | 'TEAM_MUSIC' | 'TEAM_PPT' | 'TEAM_SEARCH' | 'TEAM_VIDEO' | 'TEAM_ROUTER' | 'TEAM_TODO' | 'TEAM_PLANNER' | 'TEAM_RAG' | 'TEAM_WRITER' | 'TEAM_WRITER_NEWS' | 'TEAM_WRITER_ARTICLE' | 'TEAM_WRITER_NOVEL' | 'TEAM_WRITER_SCRIPT' | 'TEAM_WRITER_DOCUMENT' | 'EVALUATOR' | 'UNDEFINED';
  /** Agent status (1: Enabled, 2: Disabled, 3: Deleted) */
  status: 'DEFAULT' | 'ACTIVE' | 'INACTIVE' | 'DELETED' | 'DRAFT';
  /** Base Config */
  baseConfig?: PlusAiAgentConfig;
  /** Knowledge Config */
  knowledgeConfig?: AgentKnowledgeConfig;
  /** Memory Config */
  memoryConfig?: AgentMemoryConfig;
  /** Speech Config */
  speechConfig?: SpeechConfig;
  /** Tool Config */
  toolConfig?: AgentToolConfig;
  /** Team members config */
  members?: TeamAgentMembers;
  /** Category ID (foreign key to plus_ai_agent_category.id) */
  cateId?: number;
  /** Knowledge base ID (foreign key to plus_knowledge_base_info.id) */
  knowledgeBaseId?: number;
  /** Chat options (temperature, top_p, etc.) stored as JSON */
  chatOptions?: PlusChatOptions;
  /** System prompt */
  prompt?: AiAgentSystemPrompt;
}
