/** Role-Permission association VO (stores many-to-many relationship between roles and permissions) */
export interface PlusRolePermissionVO {
  /** 创建时间 */
  createdAt?: string;
  /** 更新时间 */
  updatedAt?: string;
  /** Primary key ID, auto-generated by database */
  id?: number;
  /** Universally unique identifier UUID */
  uuid?: string;
  /** Role ID (foreign key reference to plus_role.id) */
  roleId?: number;
  /** Role UUID (unique identifier for distributed system references) */
  roleUuid?: string;
  /** Permission ID (foreign key reference to plus_permission.id) */
  permissionId?: number;
  /** Permission UUID (unique identifier for distributed system references) */
  permissionUuid?: string;
  /** Permission assignment status (true=Enabled, false=Disabled) */
  enabled?: boolean;
  /** Permission assignment description (business context and purpose) */
  description?: string;
  /** Assigner user ID (operator who assigned the permission) */
  operatorId?: number;
  /** Permission assignment status (ACTIVE: available, INACTIVE: disabled, EXPIRED: expired) */
  status?: 'DEFAULT' | 'ACTIVE' | 'INACTIVE' | 'SUSPENDED' | 'DELETED';
}
