import Foundation
import SDKworkCommon

public class SdkworkBackendClient {
    private let httpClient: HttpClient
    public let workspace: WorkspaceApi
    public let contentVote: ContentVoteApi
    public let voiceSpeaker: VoiceSpeakerApi
    public let visitHistory: VisitHistoryApi
    public let vipUser: VipUserApi
    public let vipRecharge: VipRechargeApi
    public let vipRechargePackage: VipRechargePackageApi
    public let vipPointChange: VipPointChangeApi
    public let vipPackageGroup: VipPackageGroupApi
    public let vipPackage: VipPackageApi
    public let vipLevel: VipLevelApi
    public let vipLevelBenefit: VipLevelBenefitApi
    public let vipBenefit: VipBenefitApi
    public let vipBenefitUsage: VipBenefitUsageApi
    public let video: VideoApi
    public let user: UserApi
    public let userOauthAccount: UserOauthAccountApi
    public let userCoupon: UserCouponApi
    public let userCard: UserCardApi
    public let userAddress: UserAddressApi
    public let aiUsageRecord: AiUsageRecordApi
    public let shoppingCart: ShoppingCartApi
    public let shoppingCartItem: ShoppingCartItemApi
    public let refund: RefundApi
    public let payment: PaymentApi
    public let order: OrderApi
    public let orderItem: OrderItemApi
    public let aiTool: AiToolApi
    public let tenant: TenantApi
    public let databaseTable: DatabaseTableApi
    public let productSku: ProductSkuApi
    public let shortUrl: ShortUrlApi
    public let shop: ShopApi
    public let share: ShareApi
    public let shareVisitRecord: ShareVisitRecordApi
    public let shardingKey: ShardingKeyApi
    public let schema: SchemaApi
    public let rbacRole: RbacRoleApi
    public let rolePermission: RolePermissionApi
    public let invocationRecord: InvocationRecordApi
    public let rbacUserRole: RbacUserRoleApi
    public let aiPrompt: AiPromptApi
    public let project: ProjectApi
    public let product: ProductApi
    public let pptTemplate: PptTemplateApi
    public let pptTemplateSlide: PptTemplateSlideApi
    public let partner: PartnerApi
    public let chatParticipant: ChatParticipantApi
    public let ossBucket: OssBucketApi
    public let organization: OrganizationApi
    public let position: PositionApi
    public let memberRelations: MemberRelationsApi
    public let organizationMember: OrganizationMemberApi
    public let notification: NotificationApi
    public let notes: NotesApi
    public let news: NewsApi
    public let host: HostApi
    public let dnsRecord: DnsRecordApi
    public let music: MusicApi
    public let aiModelInformation: AiModelInformationApi
    public let aiModelPrice: AiModelPriceApi
    public let chatMessage: ChatMessageApi
    public let memberLevel: MemberLevelApi
    public let memberCard: MemberCardApi
    public let knowledgeBase: KnowledgeBaseApi
    public let invitationRelation: InvitationRelationApi
    public let invitationCode: InvitationCodeApi
    public let image: ImageApi
    public let chatGroup: ChatGroupApi
    public let aiGeneration: AiGenerationApi
    public let aiGenerationContent: AiGenerationContentApi
    public let file: FileApi
    public let filePart: FilePartApi
    public let fileContent: FileContentApi
    public let feeds: FeedsApi
    public let feedback: FeedbackApi
    public let favorite: FavoriteApi
    public let fileDisk: FileDiskApi
    public let diskMember: DiskMemberApi
    public let detail: DetailApi
    public let department: DepartmentApi
    public let datasource: DatasourceApi
    public let coupon: CouponApi
    public let couponTemplate: CouponTemplateApi
    public let aiConversation: AiConversationApi
    public let comment: CommentApi
    public let column: ColumnApi
    public let collection: CollectionApi
    public let collectionItem: CollectionItemApi
    public let character: CharacterApi
    public let channelResource: ChannelResourceApi
    public let channelAccount: ChannelAccountApi
    public let aiCategory: AiCategoryApi
    public let membershipCard: MembershipCardApi
    public let cardTemplate: CardTemplateApi
    public let attribute: AttributeApi
    public let aiArticle: AiArticleApi
    public let application: ApplicationApi
    public let apiKey: ApiKeyApi
    public let aiAgent: AiAgentApi
    public let aiAgentToolRelationship: AiAgentToolRelationshipApi
    public let account: AccountApi
    public let accountHistory: AccountHistoryApi
    public let searchChat: SearchChatApi
    public let pptTemplateRendering: PptTemplateRenderingApi
    public let pptTemplateChat: PptTemplateChatApi
    public let knowledgeBaseFile: KnowledgeBaseFileApi
    public let knowledgeBaseChat: KnowledgeBaseChatApi
    public let imMessage: ImMessageApi
    public let aiVoiceSpeakerGeneration: AiVoiceSpeakerGenerationApi
    public let aiVideoGeneration: AiVideoGenerationApi
    public let aiMusicGeneration: AiMusicGenerationApi
    public let aiImageGeneration: AiImageGenerationApi
    public let aiCharacterGeneration: AiCharacterGenerationApi
    public let aiAudioGeneration: AiAudioGenerationApi
    public let aiAudioEffectGeneration: AiAudioEffectGenerationApi
    public let aiChat: AiChatApi
    public let verification: VerificationApi
    public let oauthAuthentication: OauthAuthenticationApi
    public let authorization: AuthorizationApi
    public let authentication: AuthenticationApi
    public let app: AppApi
    public let aiAgentChat: AiAgentChatApi

    public init(baseURL: String) {
        self.httpClient = HttpClient(baseURL: baseURL)
        self.workspace = WorkspaceApi(client: httpClient)
        self.contentVote = ContentVoteApi(client: httpClient)
        self.voiceSpeaker = VoiceSpeakerApi(client: httpClient)
        self.visitHistory = VisitHistoryApi(client: httpClient)
        self.vipUser = VipUserApi(client: httpClient)
        self.vipRecharge = VipRechargeApi(client: httpClient)
        self.vipRechargePackage = VipRechargePackageApi(client: httpClient)
        self.vipPointChange = VipPointChangeApi(client: httpClient)
        self.vipPackageGroup = VipPackageGroupApi(client: httpClient)
        self.vipPackage = VipPackageApi(client: httpClient)
        self.vipLevel = VipLevelApi(client: httpClient)
        self.vipLevelBenefit = VipLevelBenefitApi(client: httpClient)
        self.vipBenefit = VipBenefitApi(client: httpClient)
        self.vipBenefitUsage = VipBenefitUsageApi(client: httpClient)
        self.video = VideoApi(client: httpClient)
        self.user = UserApi(client: httpClient)
        self.userOauthAccount = UserOauthAccountApi(client: httpClient)
        self.userCoupon = UserCouponApi(client: httpClient)
        self.userCard = UserCardApi(client: httpClient)
        self.userAddress = UserAddressApi(client: httpClient)
        self.aiUsageRecord = AiUsageRecordApi(client: httpClient)
        self.shoppingCart = ShoppingCartApi(client: httpClient)
        self.shoppingCartItem = ShoppingCartItemApi(client: httpClient)
        self.refund = RefundApi(client: httpClient)
        self.payment = PaymentApi(client: httpClient)
        self.order = OrderApi(client: httpClient)
        self.orderItem = OrderItemApi(client: httpClient)
        self.aiTool = AiToolApi(client: httpClient)
        self.tenant = TenantApi(client: httpClient)
        self.databaseTable = DatabaseTableApi(client: httpClient)
        self.productSku = ProductSkuApi(client: httpClient)
        self.shortUrl = ShortUrlApi(client: httpClient)
        self.shop = ShopApi(client: httpClient)
        self.share = ShareApi(client: httpClient)
        self.shareVisitRecord = ShareVisitRecordApi(client: httpClient)
        self.shardingKey = ShardingKeyApi(client: httpClient)
        self.schema = SchemaApi(client: httpClient)
        self.rbacRole = RbacRoleApi(client: httpClient)
        self.rolePermission = RolePermissionApi(client: httpClient)
        self.invocationRecord = InvocationRecordApi(client: httpClient)
        self.rbacUserRole = RbacUserRoleApi(client: httpClient)
        self.aiPrompt = AiPromptApi(client: httpClient)
        self.project = ProjectApi(client: httpClient)
        self.product = ProductApi(client: httpClient)
        self.pptTemplate = PptTemplateApi(client: httpClient)
        self.pptTemplateSlide = PptTemplateSlideApi(client: httpClient)
        self.partner = PartnerApi(client: httpClient)
        self.chatParticipant = ChatParticipantApi(client: httpClient)
        self.ossBucket = OssBucketApi(client: httpClient)
        self.organization = OrganizationApi(client: httpClient)
        self.position = PositionApi(client: httpClient)
        self.memberRelations = MemberRelationsApi(client: httpClient)
        self.organizationMember = OrganizationMemberApi(client: httpClient)
        self.notification = NotificationApi(client: httpClient)
        self.notes = NotesApi(client: httpClient)
        self.news = NewsApi(client: httpClient)
        self.host = HostApi(client: httpClient)
        self.dnsRecord = DnsRecordApi(client: httpClient)
        self.music = MusicApi(client: httpClient)
        self.aiModelInformation = AiModelInformationApi(client: httpClient)
        self.aiModelPrice = AiModelPriceApi(client: httpClient)
        self.chatMessage = ChatMessageApi(client: httpClient)
        self.memberLevel = MemberLevelApi(client: httpClient)
        self.memberCard = MemberCardApi(client: httpClient)
        self.knowledgeBase = KnowledgeBaseApi(client: httpClient)
        self.invitationRelation = InvitationRelationApi(client: httpClient)
        self.invitationCode = InvitationCodeApi(client: httpClient)
        self.image = ImageApi(client: httpClient)
        self.chatGroup = ChatGroupApi(client: httpClient)
        self.aiGeneration = AiGenerationApi(client: httpClient)
        self.aiGenerationContent = AiGenerationContentApi(client: httpClient)
        self.file = FileApi(client: httpClient)
        self.filePart = FilePartApi(client: httpClient)
        self.fileContent = FileContentApi(client: httpClient)
        self.feeds = FeedsApi(client: httpClient)
        self.feedback = FeedbackApi(client: httpClient)
        self.favorite = FavoriteApi(client: httpClient)
        self.fileDisk = FileDiskApi(client: httpClient)
        self.diskMember = DiskMemberApi(client: httpClient)
        self.detail = DetailApi(client: httpClient)
        self.department = DepartmentApi(client: httpClient)
        self.datasource = DatasourceApi(client: httpClient)
        self.coupon = CouponApi(client: httpClient)
        self.couponTemplate = CouponTemplateApi(client: httpClient)
        self.aiConversation = AiConversationApi(client: httpClient)
        self.comment = CommentApi(client: httpClient)
        self.column = ColumnApi(client: httpClient)
        self.collection = CollectionApi(client: httpClient)
        self.collectionItem = CollectionItemApi(client: httpClient)
        self.character = CharacterApi(client: httpClient)
        self.channelResource = ChannelResourceApi(client: httpClient)
        self.channelAccount = ChannelAccountApi(client: httpClient)
        self.aiCategory = AiCategoryApi(client: httpClient)
        self.membershipCard = MembershipCardApi(client: httpClient)
        self.cardTemplate = CardTemplateApi(client: httpClient)
        self.attribute = AttributeApi(client: httpClient)
        self.aiArticle = AiArticleApi(client: httpClient)
        self.application = ApplicationApi(client: httpClient)
        self.apiKey = ApiKeyApi(client: httpClient)
        self.aiAgent = AiAgentApi(client: httpClient)
        self.aiAgentToolRelationship = AiAgentToolRelationshipApi(client: httpClient)
        self.account = AccountApi(client: httpClient)
        self.accountHistory = AccountHistoryApi(client: httpClient)
        self.searchChat = SearchChatApi(client: httpClient)
        self.pptTemplateRendering = PptTemplateRenderingApi(client: httpClient)
        self.pptTemplateChat = PptTemplateChatApi(client: httpClient)
        self.knowledgeBaseFile = KnowledgeBaseFileApi(client: httpClient)
        self.knowledgeBaseChat = KnowledgeBaseChatApi(client: httpClient)
        self.imMessage = ImMessageApi(client: httpClient)
        self.aiVoiceSpeakerGeneration = AiVoiceSpeakerGenerationApi(client: httpClient)
        self.aiVideoGeneration = AiVideoGenerationApi(client: httpClient)
        self.aiMusicGeneration = AiMusicGenerationApi(client: httpClient)
        self.aiImageGeneration = AiImageGenerationApi(client: httpClient)
        self.aiCharacterGeneration = AiCharacterGenerationApi(client: httpClient)
        self.aiAudioGeneration = AiAudioGenerationApi(client: httpClient)
        self.aiAudioEffectGeneration = AiAudioEffectGenerationApi(client: httpClient)
        self.aiChat = AiChatApi(client: httpClient)
        self.verification = VerificationApi(client: httpClient)
        self.oauthAuthentication = OauthAuthenticationApi(client: httpClient)
        self.authorization = AuthorizationApi(client: httpClient)
        self.authentication = AuthenticationApi(client: httpClient)
        self.app = AppApi(client: httpClient)
        self.aiAgentChat = AiAgentChatApi(client: httpClient)
    }

    public init(config: SdkConfig) {
        self.httpClient = HttpClient(config: config)
        self.workspace = WorkspaceApi(client: httpClient)
        self.contentVote = ContentVoteApi(client: httpClient)
        self.voiceSpeaker = VoiceSpeakerApi(client: httpClient)
        self.visitHistory = VisitHistoryApi(client: httpClient)
        self.vipUser = VipUserApi(client: httpClient)
        self.vipRecharge = VipRechargeApi(client: httpClient)
        self.vipRechargePackage = VipRechargePackageApi(client: httpClient)
        self.vipPointChange = VipPointChangeApi(client: httpClient)
        self.vipPackageGroup = VipPackageGroupApi(client: httpClient)
        self.vipPackage = VipPackageApi(client: httpClient)
        self.vipLevel = VipLevelApi(client: httpClient)
        self.vipLevelBenefit = VipLevelBenefitApi(client: httpClient)
        self.vipBenefit = VipBenefitApi(client: httpClient)
        self.vipBenefitUsage = VipBenefitUsageApi(client: httpClient)
        self.video = VideoApi(client: httpClient)
        self.user = UserApi(client: httpClient)
        self.userOauthAccount = UserOauthAccountApi(client: httpClient)
        self.userCoupon = UserCouponApi(client: httpClient)
        self.userCard = UserCardApi(client: httpClient)
        self.userAddress = UserAddressApi(client: httpClient)
        self.aiUsageRecord = AiUsageRecordApi(client: httpClient)
        self.shoppingCart = ShoppingCartApi(client: httpClient)
        self.shoppingCartItem = ShoppingCartItemApi(client: httpClient)
        self.refund = RefundApi(client: httpClient)
        self.payment = PaymentApi(client: httpClient)
        self.order = OrderApi(client: httpClient)
        self.orderItem = OrderItemApi(client: httpClient)
        self.aiTool = AiToolApi(client: httpClient)
        self.tenant = TenantApi(client: httpClient)
        self.databaseTable = DatabaseTableApi(client: httpClient)
        self.productSku = ProductSkuApi(client: httpClient)
        self.shortUrl = ShortUrlApi(client: httpClient)
        self.shop = ShopApi(client: httpClient)
        self.share = ShareApi(client: httpClient)
        self.shareVisitRecord = ShareVisitRecordApi(client: httpClient)
        self.shardingKey = ShardingKeyApi(client: httpClient)
        self.schema = SchemaApi(client: httpClient)
        self.rbacRole = RbacRoleApi(client: httpClient)
        self.rolePermission = RolePermissionApi(client: httpClient)
        self.invocationRecord = InvocationRecordApi(client: httpClient)
        self.rbacUserRole = RbacUserRoleApi(client: httpClient)
        self.aiPrompt = AiPromptApi(client: httpClient)
        self.project = ProjectApi(client: httpClient)
        self.product = ProductApi(client: httpClient)
        self.pptTemplate = PptTemplateApi(client: httpClient)
        self.pptTemplateSlide = PptTemplateSlideApi(client: httpClient)
        self.partner = PartnerApi(client: httpClient)
        self.chatParticipant = ChatParticipantApi(client: httpClient)
        self.ossBucket = OssBucketApi(client: httpClient)
        self.organization = OrganizationApi(client: httpClient)
        self.position = PositionApi(client: httpClient)
        self.memberRelations = MemberRelationsApi(client: httpClient)
        self.organizationMember = OrganizationMemberApi(client: httpClient)
        self.notification = NotificationApi(client: httpClient)
        self.notes = NotesApi(client: httpClient)
        self.news = NewsApi(client: httpClient)
        self.host = HostApi(client: httpClient)
        self.dnsRecord = DnsRecordApi(client: httpClient)
        self.music = MusicApi(client: httpClient)
        self.aiModelInformation = AiModelInformationApi(client: httpClient)
        self.aiModelPrice = AiModelPriceApi(client: httpClient)
        self.chatMessage = ChatMessageApi(client: httpClient)
        self.memberLevel = MemberLevelApi(client: httpClient)
        self.memberCard = MemberCardApi(client: httpClient)
        self.knowledgeBase = KnowledgeBaseApi(client: httpClient)
        self.invitationRelation = InvitationRelationApi(client: httpClient)
        self.invitationCode = InvitationCodeApi(client: httpClient)
        self.image = ImageApi(client: httpClient)
        self.chatGroup = ChatGroupApi(client: httpClient)
        self.aiGeneration = AiGenerationApi(client: httpClient)
        self.aiGenerationContent = AiGenerationContentApi(client: httpClient)
        self.file = FileApi(client: httpClient)
        self.filePart = FilePartApi(client: httpClient)
        self.fileContent = FileContentApi(client: httpClient)
        self.feeds = FeedsApi(client: httpClient)
        self.feedback = FeedbackApi(client: httpClient)
        self.favorite = FavoriteApi(client: httpClient)
        self.fileDisk = FileDiskApi(client: httpClient)
        self.diskMember = DiskMemberApi(client: httpClient)
        self.detail = DetailApi(client: httpClient)
        self.department = DepartmentApi(client: httpClient)
        self.datasource = DatasourceApi(client: httpClient)
        self.coupon = CouponApi(client: httpClient)
        self.couponTemplate = CouponTemplateApi(client: httpClient)
        self.aiConversation = AiConversationApi(client: httpClient)
        self.comment = CommentApi(client: httpClient)
        self.column = ColumnApi(client: httpClient)
        self.collection = CollectionApi(client: httpClient)
        self.collectionItem = CollectionItemApi(client: httpClient)
        self.character = CharacterApi(client: httpClient)
        self.channelResource = ChannelResourceApi(client: httpClient)
        self.channelAccount = ChannelAccountApi(client: httpClient)
        self.aiCategory = AiCategoryApi(client: httpClient)
        self.membershipCard = MembershipCardApi(client: httpClient)
        self.cardTemplate = CardTemplateApi(client: httpClient)
        self.attribute = AttributeApi(client: httpClient)
        self.aiArticle = AiArticleApi(client: httpClient)
        self.application = ApplicationApi(client: httpClient)
        self.apiKey = ApiKeyApi(client: httpClient)
        self.aiAgent = AiAgentApi(client: httpClient)
        self.aiAgentToolRelationship = AiAgentToolRelationshipApi(client: httpClient)
        self.account = AccountApi(client: httpClient)
        self.accountHistory = AccountHistoryApi(client: httpClient)
        self.searchChat = SearchChatApi(client: httpClient)
        self.pptTemplateRendering = PptTemplateRenderingApi(client: httpClient)
        self.pptTemplateChat = PptTemplateChatApi(client: httpClient)
        self.knowledgeBaseFile = KnowledgeBaseFileApi(client: httpClient)
        self.knowledgeBaseChat = KnowledgeBaseChatApi(client: httpClient)
        self.imMessage = ImMessageApi(client: httpClient)
        self.aiVoiceSpeakerGeneration = AiVoiceSpeakerGenerationApi(client: httpClient)
        self.aiVideoGeneration = AiVideoGenerationApi(client: httpClient)
        self.aiMusicGeneration = AiMusicGenerationApi(client: httpClient)
        self.aiImageGeneration = AiImageGenerationApi(client: httpClient)
        self.aiCharacterGeneration = AiCharacterGenerationApi(client: httpClient)
        self.aiAudioGeneration = AiAudioGenerationApi(client: httpClient)
        self.aiAudioEffectGeneration = AiAudioEffectGenerationApi(client: httpClient)
        self.aiChat = AiChatApi(client: httpClient)
        self.verification = VerificationApi(client: httpClient)
        self.oauthAuthentication = OauthAuthenticationApi(client: httpClient)
        self.authorization = AuthorizationApi(client: httpClient)
        self.authentication = AuthenticationApi(client: httpClient)
        self.app = AppApi(client: httpClient)
        self.aiAgentChat = AiAgentChatApi(client: httpClient)
    }

    public func setApiKey(_ apiKey: String) -> SdkworkBackendClient {
        httpClient.setApiKey(apiKey)
        return self
    }

    public func setAuthToken(_ token: String) -> SdkworkBackendClient {
        httpClient.setAuthToken(token)
        return self
    }

    public func setAccessToken(_ token: String) -> SdkworkBackendClient {
        httpClient.setAccessToken(token)
        return self
    }

    public func setHeader(_ key: String, value: String) -> SdkworkBackendClient {
        httpClient.setHeader(key, value: value)
        return self
    }
}
