package com.sdkwork.backend

data class AgentExecutionContext(
    val id: String? = null,
    val bizType: String? = null,
    val uuid: String? = null,
    val maxFlowSteps: Int? = null,
    val flowSteps: Int? = null,
    val threads: Int? = null,
    val createAt: String? = null,
    val maxDuration: Int? = null,
    val listeners: List<ChatMessageListener>? = null,
    val state: String? = null,
    val chatContext: ChatContext? = null,
    val shardingContext: ShardingContext? = null,
    val flow: Flow? = null,
    val root: AgentExecutionContext? = null,
    val parent: AgentExecutionContext? = null,
    val pre: PlusAgent? = null,
    val current: PlusAgent? = null,
    val responseHandler: ChatResponseHandler? = null,
    val project: PlusProjectObject? = null,
    val disk: PlusDiskObject? = null,
    val diskRootFile: PlusFileObject? = null,
    val completed: Boolean? = null,
    val running: Boolean? = null,
    val expired: Boolean? = null,
    val waiting: Boolean? = null,
    val failed: Boolean? = null,
    val paused: Boolean? = null,
    val end: Boolean? = null,
    val init: Boolean? = null,
    val agentSCOPES: Map<String, AgentScope>? = null,
    val overSteps: Boolean? = null
)
