package com.sdkwork.backend

data class ModelConfig(
    val id: Int? = null,
    val uuid: String? = null,
    val weight: Int? = null,
    val channel: String? = null,
    val product: String? = null,
    val agent: AgentAccountConfig? = null,
    val appStore: AppStoreAccountConfig? = null,
    val apikey: ApiKeyAccountConfig? = null,
    val audio: AudioAccountConfig? = null,
    val cloud: CloudAccountConfig? = null,
    val datasource: DatasourceAccountConfig? = null,
    val embedding: EmbeddingAccountConfig? = null,
    val files: FilesAccountConfig? = null,
    val im: ImAccountConfig? = null,
    val image: ImageAccountConfig? = null,
    val iot: IotAccountConfig? = null,
    val knowledge: KnowledgeAccountConfig? = null,
    val llm: LlmAccountConfig? = null,
    val memory: MemoryAccountConfig? = null,
    val moderation: ModerationAccountConfig? = null,
    val music: MusicAccountConfig? = null,
    val miniProgram: MiniProgramAccountConfig? = null,
    val news: NewsAccountConfig? = null,
    val ocr: OcrAccountConfig? = null,
    val official: OfficialAccountConfig? = null,
    val oss: OssAccountConfig? = null,
    val pay: PayAccountConfig? = null,
    val rtc: RtcAccountConfig? = null,
    val search: SearchAccountConfig? = null,
    val sms: SmsAccountConfig? = null,
    val tool: ToolAccountConfig? = null,
    val vector: VectorAccountConfig? = null,
    val video: VideoAccountConfig? = null,
    val voice: AudioAccountConfig? = null,
    val resources: ChannelResourceInfo? = null,
    val properties: Map<String, Any>? = null,
    val oauth: OAuthAccountConfig? = null
)
