package com.sdkwork.backend

data class OfficialAccountConfig(
    val id: Int? = null,
    val uuid: String? = null,
    val region: String? = null,
    val weight: Int? = null,
    val channel: String? = null,
    val product: String? = null,
    val functions: List<String>? = null,
    val metadata: AccountConfigMetadata? = null,
    val properties: Map<String, Any>? = null,
    val authProvider: String? = null,
    val appId: String? = null,
    val appSecret: String? = null,
    val token: String? = null,
    val redirectUri: String? = null,
    val scope: String? = null,
    val isServiceAccount: Boolean? = null,
    val teamId: String? = null,
    val keyId: String? = null,
    val privateKey: String? = null,
    val publicKey: String? = null,
    val secret: String? = null,
    val aesKey: String? = null,
    val qrCodeUrl: String? = null,
    val originalId: String? = null,
    val notifyUrl: String? = null,
    val securityModeEnabled: Boolean? = null,
    val accessToken: String? = null,
    val accessTokenExpiresIn: Int? = null,
    val accessTokenFetchTime: Int? = null,
    val jsSdkEnabled: Boolean? = null,
    val jsApiDomain: String? = null,
    val encodingAESKey: String? = null
)
