package com.sdkwork.backend

data class PlusUser(
    val tenantId: Int? = null,
    val organizationId: Int? = null,
    val dataScope: String? = null,
    val id: Int? = null,
    val uuid: String? = null,
    val createdAt: String? = null,
    val updatedAt: String? = null,
    val v: Int? = null,
    val username: String? = null,
    val nickname: String? = null,
    val password: String? = null,
    val platform: String? = null,
    val type: String? = null,
    val gender: String? = null,
    val faceImage: ImageMediaResource? = null,
    val faceVideo: VideoMediaResource? = null,
    val salt: String? = null,
    val scene: String? = null,
    val email: String? = null,
    val phone: String? = null,
    val countryCode: String? = null,
    val provinceCode: String? = null,
    val cityCode: String? = null,
    val districtCode: String? = null,
    val address: String? = null,
    val bio: String? = null,
    val birthDate: String? = null,
    val oauthUserInfo: GetUserInfoResponse? = null,
    val status: String? = null,
    val roles: List<PlusRole>? = null,
    val metadata: UserMetadata? = null,
    val socialInfoList: SocialInfoList? = null,
    val roleCodes: List<String>? = null,
    val authorities: List<GrantedAuthority>? = null
)
