package com.sdkwork.backend

data class PlusGameRoomVO(
    val createdAt: String? = null,
    val updatedAt: String? = null,
    val roomId: Int? = null,
    val userId: Int? = null,
    val definitionId: Int? = null,
    val gameType: String? = null,
    val gameModeCode: String? = null,
    val seasonKey: String? = null,
    val roomNo: String? = null,
    val name: String? = null,
    val roomType: String? = null,
    val status: String? = null,
    val visibility: String? = null,
    val seatCount: Int? = null,
    val currentPlayerCount: Int? = null,
    val minStartPlayerCount: Int? = null,
    val hostSeatNo: Int? = null,
    val clubId: Int? = null,
    val tournamentId: Int? = null,
    val regionCode: String? = null,
    val currentMatchId: Int? = null,
    val currentRoundNo: Int? = null,
    val plannedRoundCount: Int? = null,
    val finishedRoundCount: Int? = null,
    val ranked: Boolean? = null,
    val allowSpectator: Boolean? = null,
    val allowRobot: Boolean? = null,
    val allowTrusteeship: Boolean? = null,
    val leaderboardEligible: Boolean? = null,
    val replayEnabled: Boolean? = null,
    val spectatorCount: Int? = null,
    val inviteCode: String? = null,
    val ruleConfig: Map<String, Any>? = null,
    val extData: Map<String, Any>? = null,
    val startedAt: String? = null,
    val endedAt: String? = null,
    val lastActiveAt: String? = null
)
