package com.sdkwork.backend

data class PlusGameGrowthAccountVO(
    val createdAt: String? = null,
    val updatedAt: String? = null,
    val accountId: Int? = null,
    val userId: Int? = null,
    val accountType: String? = null,
    val gameType: String? = null,
    val gameModeCode: String? = null,
    val seasonKey: String? = null,
    val currentLevelConfigId: Int? = null,
    val currentLevelNo: Int? = null,
    val currentLevelCode: String? = null,
    val currentLevelName: String? = null,
    val currentTitle: String? = null,
    val currentBadgeCode: String? = null,
    val currentExp: Int? = null,
    val totalExp: Int? = null,
    val currentLevelStartExp: Int? = null,
    val nextLevelRequiredExp: Int? = null,
    val expToNextLevel: Int? = null,
    val progressPercent: Double? = null,
    val peakLevelNo: Int? = null,
    val peakExp: Int? = null,
    val levelUpCount: Int? = null,
    val rewardClaimedCount: Int? = null,
    val lastGainAt: String? = null,
    val lastLevelUpAt: String? = null,
    val lastResetAt: String? = null,
    val active: Boolean? = null,
    val lastClaimedLevelNo: Int? = null,
    val lastRewardClaimedAt: String? = null,
    val lastRewardIssuedAt: String? = null,
    val lastClaimedRewardLevelCode: String? = null,
    val lastClaimedRewardLevelName: String? = null,
    val lastClaimedRewardSummary: Map<String, Any>? = null,
    val lastClaimedRewardConfig: Map<String, Any>? = null,
    val extData: Map<String, Any>? = null
)
