package com.sdkwork.backend

data class PlusGameRecordVO(
    val createdAt: String? = null,
    val updatedAt: String? = null,
    val recordId: Int? = null,
    val roomId: Int? = null,
    val matchId: Int? = null,
    val userId: Int? = null,
    val gameType: String? = null,
    val gameModeCode: String? = null,
    val seasonKey: String? = null,
    val clubId: Int? = null,
    val tournamentId: Int? = null,
    val regionCode: String? = null,
    val seatNo: Int? = null,
    val teamNo: Int? = null,
    val resultType: String? = null,
    val rankNo: Int? = null,
    val nicknameSnapshot: String? = null,
    val avatarUrl: String? = null,
    val winner: Boolean? = null,
    val escaped: Boolean? = null,
    val leaderboardEligible: Boolean? = null,
    val actionCount: Int? = null,
    val moveCount: Int? = null,
    val scoreBefore: Int? = null,
    val scoreDelta: Int? = null,
    val scoreAfter: Int? = null,
    val ratingBefore: Int? = null,
    val ratingDelta: Int? = null,
    val ratingAfter: Int? = null,
    val chipsBefore: Int? = null,
    val chipsDelta: Int? = null,
    val chipsAfter: Int? = null,
    val joinedAt: String? = null,
    val finishedAt: String? = null,
    val bestRankSnapshot: Int? = null,
    val settlementData: Map<String, Any>? = null,
    val honorSnapshot: Map<String, Any>? = null
)
