package com.sdkwork.backend

data class PlusGameGrowthRecordVO(
    val createdAt: String? = null,
    val updatedAt: String? = null,
    val recordId: Int? = null,
    val userId: Int? = null,
    val accountType: String? = null,
    val gameType: String? = null,
    val gameModeCode: String? = null,
    val seasonKey: String? = null,
    val roomId: Int? = null,
    val matchId: Int? = null,
    val tournamentId: Int? = null,
    val sourceType: String? = null,
    val bizNo: String? = null,
    val reason: String? = null,
    val expBefore: Int? = null,
    val expDelta: Int? = null,
    val expAfter: Int? = null,
    val totalExpBefore: Int? = null,
    val totalExpDelta: Int? = null,
    val totalExpAfter: Int? = null,
    val levelConfigIdBefore: Int? = null,
    val levelConfigIdAfter: Int? = null,
    val levelNoBefore: Int? = null,
    val levelNoAfter: Int? = null,
    val levelCodeBefore: String? = null,
    val levelCodeAfter: String? = null,
    val levelUp: Boolean? = null,
    val operatorUserId: Int? = null,
    val occurredAt: String? = null,
    val settlementData: Map<String, Any>? = null,
    val extData: Map<String, Any>? = null
)
