package com.sdkwork.backend

data class PlusOrderVO(
    val createdAt: String? = null,
    val updatedAt: String? = null,
    val id: Int? = null,
    val orderType: String? = null,
    val userId: Int? = null,
    val subject: String? = null,
    val orderSn: String? = null,
    val transactionId: String? = null,
    val outTradeNo: String? = null,
    val totalAmount: Double? = null,
    val paidAmount: Double? = null,
    val paidPointsAmount: Int? = null,
    val status: String? = null,
    val payTime: String? = null,
    val expireTime: String? = null,
    val contentType: String? = null,
    val contentId: Int? = null,
    val taskCode: String? = null,
    val dispatchMode: String? = null,
    val dispatchStatus: String? = null,
    val workerUserId: Int? = null,
    val dispatcherUserId: Int? = null,
    val acceptedTime: String? = null,
    val serviceStartTime: String? = null,
    val dispatchExpireTime: String? = null,
    val taskPayload: Map<String, Any>? = null,
    val payObjects: ClientPayObjects? = null
)
