package com.sdkwork.backend

data class PlusGameMatchVO(
    val createdAt: String? = null,
    val updatedAt: String? = null,
    val matchId: Int? = null,
    val definitionId: Int? = null,
    val roomId: Int? = null,
    val gameType: String? = null,
    val gameModeCode: String? = null,
    val seasonKey: String? = null,
    val matchNo: String? = null,
    val roomType: String? = null,
    val status: String? = null,
    val ranked: Boolean? = null,
    val totalPlayerCount: Int? = null,
    val clubId: Int? = null,
    val tournamentId: Int? = null,
    val regionCode: String? = null,
    val currentRoundNo: Int? = null,
    val maxRoundCount: Int? = null,
    val currentTurnSeatNo: Int? = null,
    val dealerSeatNo: Int? = null,
    val winnerSeatNo: Int? = null,
    val winnerUserId: Int? = null,
    val replayId: Int? = null,
    val actionCount: Int? = null,
    val moveCount: Int? = null,
    val leaderboardEligible: Boolean? = null,
    val validForStats: Boolean? = null,
    val resultConfirmed: Boolean? = null,
    val abnormalFinished: Boolean? = null,
    val invalidReason: String? = null,
    val startedAt: String? = null,
    val settledAt: String? = null,
    val endedAt: String? = null,
    val durationSeconds: Int? = null
)
