package com.sdkwork.backend

data class PlusChatMessageVO(
    val createdAt: String? = null,
    val updatedAt: String? = null,
    val id: Int? = null,
    val body: MessageBody? = null,
    val role: String? = null,
    val type: String? = null,
    val status: String? = null,
    val conversationId: Int? = null,
    val conversationUuid: String? = null,
    val userId: Int? = null,
    val senderId: Int? = null,
    val sender: Participant? = null,
    val receiver: Participant? = null,
    val receiverId: Int? = null,
    val groupId: Int? = null,
    val parentMessageId: Int? = null,
    val children: List<PlusChatMessageVO>? = null,
    val metadata: Map<String, Any>? = null,
    val tokenCount: Int? = null,
    val sendAt: String? = null,
    val receiveAt: String? = null,
    val readAt: String? = null,
    val processingTime: Int? = null,
    val isError: Boolean? = null,
    val errorCode: String? = null,
    val errorMessage: String? = null,
    val modelId: Int? = null,
    val model: String? = null,
    val temperature: Double? = null,
    val usedRag: Boolean? = null,
    val chatOptions: PlusChatOptions? = null,
    val channelId: String? = null,
    val agentId: Int? = null,
    val knowledgeBaseId: Int? = null,
    val datasourceId: Int? = null,
    val agentType: String? = null,
    val agentBizType: String? = null,
    val channelMsgId: String? = null,
    val channelClientMsgId: String? = null,
    val channelMsgSeq: Int? = null,
    val conversationType: String? = null,
    val feedbackMetadata: FeedbackMetadata? = null
)
