package com.sdkwork.backend

data class PlusGameActionRecordVO(
    val createdAt: String? = null,
    val updatedAt: String? = null,
    val actionId: Int? = null,
    val roomId: Int? = null,
    val matchId: Int? = null,
    val roundId: Int? = null,
    val gameType: String? = null,
    val roomType: String? = null,
    val replayId: Int? = null,
    val tournamentId: Int? = null,
    val playerUserId: Int? = null,
    val seatNo: Int? = null,
    val playerType: String? = null,
    val seqNo: Int? = null,
    val turnNo: Int? = null,
    val phaseName: String? = null,
    val actionType: String? = null,
    val actionCode: String? = null,
    val notation: String? = null,
    val targetSeatNo: Int? = null,
    val sourcePosition: String? = null,
    val targetPosition: String? = null,
    val consumeMillis: Int? = null,
    val validAction: Boolean? = null,
    val systemAction: Boolean? = null,
    val timeoutAction: Boolean? = null,
    val actionAt: String? = null,
    val actionPayload: Map<String, Any>? = null,
    val beforeState: Map<String, Any>? = null,
    val afterState: Map<String, Any>? = null
)
