package com.sdkwork.backend

data class PlusGameLeaderboardVO(
    val createdAt: String? = null,
    val updatedAt: String? = null,
    val leaderboardId: Int? = null,
    val leaderboardNo: String? = null,
    val name: String? = null,
    val shortName: String? = null,
    val gameType: String? = null,
    val gameModeCode: String? = null,
    val rankingType: String? = null,
    val periodType: String? = null,
    val scopeType: String? = null,
    val scopeOwnerId: Int? = null,
    val scopeName: String? = null,
    val seasonKey: String? = null,
    val clubId: Int? = null,
    val tournamentId: Int? = null,
    val regionCode: String? = null,
    val status: String? = null,
    val rankedOnly: Boolean? = null,
    val includeFriendRoom: Boolean? = null,
    val includeTournamentRoom: Boolean? = null,
    val includeClubRoom: Boolean? = null,
    val minMatchCount: Int? = null,
    val minWinRateMatchCount: Int? = null,
    val totalParticipantCount: Int? = null,
    val periodStartAt: String? = null,
    val periodEndAt: String? = null,
    val publishedAt: String? = null,
    val settledAt: String? = null,
    val entries: List<PlusGameLeaderboardEntryVO>? = null
)
