package com.sdkwork.backend

data class PlusGameDefinitionForm(
    val code: String? = null,
    val gameType: String? = null,
    val category: String? = null,
    val name: String? = null,
    val alias: String? = null,
    val gameModeCode: String? = null,
    val description: String? = null,
    val ruleSummary: String? = null,
    val minPlayers: Int? = null,
    val maxPlayers: Int? = null,
    val seatCount: Int? = null,
    val teamCount: Int? = null,
    val defaultRoundCount: Int? = null,
    val turnBased: Boolean? = null,
    val ranked: Boolean? = null,
    val supportsSpectator: Boolean? = null,
    val supportsTrusteeship: Boolean? = null,
    val supportsRobot: Boolean? = null,
    val supportsReplay: Boolean? = null,
    val supportsFriendRoom: Boolean? = null,
    val supportsTournament: Boolean? = null,
    val supportsClub: Boolean? = null,
    val supportsPractice: Boolean? = null,
    val difficultyLevel: Int? = null,
    val tutorialUrl: String? = null,
    val rankingType: String? = null,
    val defaultRuleConfig: Map<String, Any>? = null,
    val metadata: Map<String, Any>? = null,
    val supportedLeaderboardPeriods: List<String>? = null,
    val enabled: Boolean? = null
)
