package com.sdkwork.backend

data class PlusGameTournamentVO(
    val createdAt: String? = null,
    val updatedAt: String? = null,
    val tournamentId: Int? = null,
    val tournamentNo: String? = null,
    val name: String? = null,
    val shortName: String? = null,
    val description: String? = null,
    val gameType: String? = null,
    val gameModeCode: String? = null,
    val tournamentType: String? = null,
    val status: String? = null,
    val organizerUserId: Int? = null,
    val clubId: Int? = null,
    val seasonKey: String? = null,
    val regionCode: String? = null,
    val minPlayerCount: Int? = null,
    val maxPlayerCount: Int? = null,
    val teamSize: Int? = null,
    val registrationRequired: Boolean? = null,
    val ranked: Boolean? = null,
    val replayEnabled: Boolean? = null,
    val signUpStartAt: String? = null,
    val signUpEndAt: String? = null,
    val startAt: String? = null,
    val endAt: String? = null,
    val winnerUserId: Int? = null,
    val winnerClubId: Int? = null,
    val totalParticipantCount: Int? = null,
    val totalMatchCount: Int? = null,
    val registeredCount: Int? = null,
    val checkedInCount: Int? = null,
    val playingCount: Int? = null,
    val advancedCount: Int? = null,
    val eliminatedCount: Int? = null,
    val finishedCount: Int? = null,
    val withdrawnCount: Int? = null
)
