package com.sdkwork.backend.api

import com.sdkwork.backend.http.HttpClient

/**
 * API modules for sdkwork-backend-sdk
 */
class Api(private val client: HttpClient) {
    val workspace: WorkspaceApi = WorkspaceApi(client)
    val vote: VoteApi = VoteApi(client)
    val voice: VoiceApi = VoiceApi(client)
    val visitHistory: VisitHistoryApi = VisitHistoryApi(client)
    val vip: VipApi = VipApi(client)
    val video: VideoApi = VideoApi(client)
    val user: UserApi = UserApi(client)
    val usage: UsageApi = UsageApi(client)
    val trade: TradeApi = TradeApi(client)
    val tool: ToolApi = ToolApi(client)
    val tenant: TenantApi = TenantApi(client)
    val table: TableApi = TableApi(client)
    val sku: SkuApi = SkuApi(client)
    val skill: SkillApi = SkillApi(client)
    val shortUrl: ShortUrlApi = ShortUrlApi(client)
    val shop: ShopApi = ShopApi(client)
    val share: ShareApi = ShareApi(client)
    val sharding: ShardingApi = ShardingApi(client)
    val security: SecurityApi = SecurityApi(client)
    val schema: SchemaApi = SchemaApi(client)
    val role: RoleApi = RoleApi(client)
    val record: RecordApi = RecordApi(client)
    val rbac: RbacApi = RbacApi(client)
    val prompt: PromptApi = PromptApi(client)
    val project: ProjectApi = ProjectApi(client)
    val product: ProductApi = ProductApi(client)
    val ppt: PptApi = PptApi(client)
    val permission: PermissionApi = PermissionApi(client)
    val partner: PartnerApi = PartnerApi(client)
    val participant: ParticipantApi = ParticipantApi(client)
    val oss: OssApi = OssApi(client)
    val organization: OrganizationApi = OrganizationApi(client)
    val organizationMember: OrganizationMemberApi = OrganizationMemberApi(client)
    val notification: NotificationApi = NotificationApi(client)
    val note: NoteApi = NoteApi(client)
    val news: NewsApi = NewsApi(client)
    val net: NetApi = NetApi(client)
    val music: MusicApi = MusicApi(client)
    val model: ModelApi = ModelApi(client)
    val message: MessageApi = MessageApi(client)
    val member: MemberApi = MemberApi(client)
    val knowledgeBase: KnowledgeBaseApi = KnowledgeBaseApi(client)
    val invitation: InvitationApi = InvitationApi(client)
    val image: ImageApi = ImageApi(client)
    val im: ImApi = ImApi(client)
    val generation: GenerationApi = GenerationApi(client)
    val game: GameApi = GameApi(client)
    val file: FileApi = FileApi(client)
    val feed: FeedApi = FeedApi(client)
    val feedback: FeedbackApi = FeedbackApi(client)
    val favorite: FavoriteApi = FavoriteApi(client)
    val disk: DiskApi = DiskApi(client)
    val detail: DetailApi = DetailApi(client)
    val department: DepartmentApi = DepartmentApi(client)
    val datasource: DatasourceApi = DatasourceApi(client)
    val coupon: CouponApi = CouponApi(client)
    val conversation: ConversationApi = ConversationApi(client)
    val contentWriting: ContentWritingApi = ContentWritingApi(client)
    val comment: CommentApi = CommentApi(client)
    val column: ColumnApi = ColumnApi(client)
    val collection: CollectionApi = CollectionApi(client)
    val collectionItem: CollectionItemApi = CollectionItemApi(client)
    val chat: ChatApi = ChatApi(client)
    val character: CharacterApi = CharacterApi(client)
    val channel: ChannelApi = ChannelApi(client)
    val category: CategoryApi = CategoryApi(client)
    val card: CardApi = CardApi(client)
    val attribute: AttributeApi = AttributeApi(client)
    val article: ArticleApi = ArticleApi(client)
    val app: AppApi = AppApi(client)
    val apikey: ApikeyApi = ApikeyApi(client)
    val agent: AgentApi = AgentApi(client)
    val account: AccountApi = AccountApi(client)
    val system: SystemApi = SystemApi(client)
    val search: SearchApi = SearchApi(client)
    val auth: AuthApi = AuthApi(client)
}
